2025-Ureca-Snac/snac-server

build.gradle, src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/common/advice/GlobalAdvice.java, src/main/java/com/ureca/snac/common/exception/BusinessException.java, src/main/java/com/ureca/snac/finance/controller/BankController.java, src/main/java/com/ureca/snac/finance/controller/request/CreateBankRequest.java, src/main/java/com/ureca/snac/finance/controller/request/UpdateBankRequest.java, src/main/java/com/ureca/snac/finance/entity/Bank.java, src/main/java/com/ureca/snac/finance/exception/BankNotFoundException.java, src/main/java/com/ureca/snac/finance/repository/BankRepository.java, src/main/java/com/ureca/snac/finance/service/BankService.java, src/main/java/com/ureca/snac/finance/service/BankServiceImpl.java, src/main/java/com/ureca/snac/finance/service/response/BankResponse.java
1. 은행(Bank) 엔티티에 대한 CRUD API 구현
2. 예외 (BankNotFoundException, BusinessException) 추가
- POST /api/banks: 은행 생성 API 구현
- GET /api/banks/{bankId}: 단일 은행 조회 API 구현
- GET /api/banks: 은행 목록 조회 API 구현
- PATCH /api/banks/{bankId}: 은행 정보 수정 API 구현
- DELETE /api/banks/{bankId}: 은행 삭제 API 구현
- BankNotFoundException 커스텀 예외 추가 및 전역 핸들러 처리
- 
-
=> [feat] 은행 CRUD API 구현

build.gradle, src/main/java/com/ureca/snac/auth/config/SnsConfig.java, src/main/java/com/ureca/snac/auth/controller/JoinController.java, src/main/java/com/ureca/snac/auth/controller/SnsController.java, src/main/java/com/ureca/snac/auth/dto/request/JoinRequest.java, src/main/java/com/ureca/snac/auth/dto/request/PhoneRequest.java, src/main/java/com/ureca/snac/auth/dto/response/VerificationCodeResponse.java, src/main/java/com/ureca/snac/auth/exception/AuthExceptionHandler.java, src/main/java/com/ureca/snac/auth/exception/SmsSendFailedException.java, src/main/java/com/ureca/snac/auth/service/JoinService.java, src/main/java/com/ureca/snac/auth/service/JoinServiceImpl.java, src/main/java/com/ureca/snac/auth/service/SnsService.java, src/main/java/com/ureca/snac/common/BaseCode.java, src/main/resources/application.yml
feat: AWS SNS 클라이언트 구성을 위한 SnsConfig 구현
feat: SMS 전송 및 유효성 검증을 담당하는 SnsService 생성
feat: SMS 관련 성공/실패 상황을 위한 예외 및 BaseCode 정의
feat: 휴대폰 인증을 위한 PhoneRequest, VerificationCodeResponse DTO 추가
feat: application.yml에 AWS SNS 설정값(플레이스홀더) 추가
refactor: 회원가입 관련 서비스 리팩토링: 비즈니스 로직 분리하여 JoinServiceImpl로 이전
fix: 리팩토링된 가입 플로우에 맞게 JoinController 수정
fix: AuthExceptionHandler를 개선하여 ResponseEntity로 올바른 HTTP 응답 반환
- 
- 
-
=> feat: AWS SNS를 이용한 인증번호 발송(SNS 연동) 기능 추가

src/main/java/com/ureca/snac/board/controller/CardController.java, src/main/java/com/ureca/snac/board/controller/CardControllerSwagger.java, src/main/java/com/ureca/snac/board/entity/Card.java, src/main/java/com/ureca/snac/board/repository/CardRepository.java, src/main/java/com/ureca/snac/board/repository/CardRepositoryCustom.java, src/main/java/com/ureca/snac/board/repository/CardRepositoryImpl.java, src/main/java/com/ureca/snac/board/service/CardService.java, src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
1. 판매글/구매글 관련 API에 Swagger 추가
2. 커서 기반 페이징 API에 가격 필터링(`List<PriceRange>`) 기능 추가
3. PriceRange.ALL 포함 시 전체 가격대 조회되도록 로직 개선
- 기존 단일 가격 필터(PriceRange)에서 다중 가격 필터(List 형태)를 받을 수 있도록 API 개선
-  여러 구간 중 하나라도 해당되면 포함 (OR 조건), ALL 포함 시 전체 가격 조회
- QueryDSL 조건문에서 priceRangeIn(...) 로 다중 조건 처리
- 스크롤 조회 API에서 커서 기반 페이징 동작을 명확히 문서화
-  최초 요청 시 lastCardId, lastUpdatedAt 없이 가능
- 이후 더보기 요청 시 두 값 모두 필요함
- 
-
=> [feat] 구매 및 판매글 가격 필터링 보완

build.gradle, src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/notification/config/RabbitMqConfig.java, src/main/java/com/ureca/snac/notification/dto/NotificationMessage.java, src/main/java/com/ureca/snac/notification/entity/Notification.java, src/main/java/com/ureca/snac/notification/entity/NotificationType.java, src/main/java/com/ureca/snac/notification/repository/NotificationRepository.java, src/main/java/com/ureca/snac/notification/service/NotificationService.java, src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java, src/main/java/com/ureca/snac/trade/controller/TradeController.java, src/main/java/com/ureca/snac/trade/dto/AcceptTradeRequest.java, src/main/java/com/ureca/snac/trade/dto/TradeRequest.java, src/main/java/com/ureca/snac/trade/dto/TradeResponse.java, src/main/java/com/ureca/snac/trade/entity/Trade.java, src/main/java/com/ureca/snac/trade/exception/DuplicateTradeRequestException.java, src/main/java/com/ureca/snac/trade/exception/TradeNotFoundException.java, src/main/java/com/ureca/snac/trade/exception/TradePermissionDeniedException.java, src/main/java/com/ureca/snac/trade/exception/TradeSelfRequestException.java, src/main/java/com/ureca/snac/trade/repository/TradeRepository.java, src/main/java/com/ureca/snac/trade/service/TradeService.java, src/main/java/com/ureca/snac/trade/service/TradeServiceImpl.java, src/main/resources/application.yml
1. 구매/판매 card 를 통해 판매자 또는 구매자가 거래 신청을 할 수 있습니다.
2. 거래 신청 시 대상자는 알림을 받습니다. 동시에 거래가 생성됩니다. 
3. 요청 수락시 요청자는 알림을 받습니다.
4. 요청 수락시 거래 상태가 요청됨에서 수락됨으로 변경됩니다.
5. 알림 서비스를 위한 RabbitMQ 세팅했습니다.
6. 알림이 RabbitMQ 큐에 등록되며, 알림 테이블에 등록됩니다.
- 
- 
-
=> [feat]  구매/판매 card를 통한 거래 신청(생성) 및 수락 기능 및 알림 생성 기능 

src/main/java/com/ureca/snac/trade/controller/AttachmentController.java, src/main/java/com/ureca/snac/trade/service/AttachmentService.java, src/main/java/com/ureca/snac/trade/service/AttachmentServiceImpl.java, src/main/java/com/ureca/snac/trade/service/BasicTradeServiceImpl.java
- sendTradeData 로직 내에서 스크린샷 파일 업로드는 AttachmentService로 분리
- AttachmentService는 권한 및 중복 검증, S3 업로드, 엔티티 저장을 전담
- sendTradeData는 비즈니스 상태 전이만 수행하도록 변경 (판매자 지정 및 DATA_SENT 전이)
- 기존 AttachmentController의 upload 엔드포인트는 사용하지 않음 (삭제)
- AttachmentService의 upload 반환형은 void로 변경
- 
- 
- 
-
=> [feat] 거래 데이터 전송 로직에 이미지 첨부 기능 연결

src/main/java/com/ureca/snac/auth/service/SnsService.java, src/main/java/com/ureca/snac/auth/service/SnsServiceImpl.java, src/main/java/com/ureca/snac/common/advice/GlobalAdvice.java, src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java, src/main/java/com/ureca/snac/trade/controller/BasicTradeControllerSwagger.java, src/main/java/com/ureca/snac/trade/controller/request/ClaimBuyRequest.java, src/main/java/com/ureca/snac/trade/repository/TradeRepository.java, src/main/java/com/ureca/snac/trade/service/BasicTradeService.java, src/main/java/com/ureca/snac/trade/service/BasicTradeServiceImpl.java, src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
1. 판매자 거래 요청(구매글 승인) 기능 추가
2. 거래 상태별 문자 알림 기능 구현
- POST /api/trades/buy/accept 엔드포인트 추가
- 요청 파라미터로 cardId를 받아 해당 구매글에 판매자 승인 처리
- SMS 알림 기능
- 거래 요청(구매글 승인), 데이터 전송, 거래 완료 등 주요 상태 알람
- 
-
=> [feat] 카드 거래 상태별 거래 진행 차단 및 단계별 문자 알림 구현

src/main/java/com/ureca/snac/asset/entity/AssetHistory.java, src/main/java/com/ureca/snac/asset/entity/SourceDomain.java, src/main/java/com/ureca/snac/asset/event/AssetChangedEvent.java, src/main/java/com/ureca/snac/asset/service/AssetChangedEventFactory.java, src/main/java/com/ureca/snac/asset/service/AssetHistoryService.java, src/main/java/com/ureca/snac/dev/service/DevToolServiceImpl.java, src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java, src/main/java/com/ureca/snac/payment/service/PaymentServiceImpl.java, src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
1. SourceDomain Enum 도입, 타입 안정성
2. AssetChangedEventFactory 도입 
3. 충전 취소, 거래 (구매) 자산내역 기록 연동
- 이벤트 생성 로직을 중앙에서 관리하는 팩토리 클래스, DDD 도메인 서비스에 따라서 사용 코드중복 제거 서비스 책임 분리
- 단일 책임원칙 고려 각 서비스는 '이벤트를 언제 발행?' 팩토리는 '이벤트를 어떻게 만들게?'
=> [feat, refactor] 자산 내역 api 연동

src/main/java/com/ureca/snac/auth/config/SecurityConfig.java, src/main/java/com/ureca/snac/auth/service/CustomOAuth2UserService.java
- 기존에는 state를 무조건 로그인 시 이메일 추출 용도로만 썼다면, 이제는 JWT 파싱 성공 여부로 연동 플로우 vs 로그인 플로우를 분기
- 나중의 소셜 회원가입 대비 확장성 있는 리팩토링
**소셜 “연동” 플로우 분리**
isLinking == true인 경우,
이미 다른 계정에 해당 providerId가 연결되어 있는지(Repositoy의 findByNaverId/findByGoogleId/findByKakaoId) 체크
중복 연결 시 예외 발생
JWT에서 뽑은 이메일로 현재 계정(Member) 조회
member.updateSocialId(...) 호출해 연동 정보 저장
new CustomOAuth2User(...) 반환
**소셜 “로그인” 플로우 정비**
isLinking == false인 경우,
소셜 ID로 기존 회원 조회 (existingMember)
존재하면 곧바로 로그인 처리(CustomOAuth2User 반환)
없으면 다시 한 번 state를 JWT로 디코딩해 이메일 획득
이메일로 회원 조회 → updateSocialId(...) → 저장 → CustomOAuth2User 반환
그마저 실패하면 예외 발생
- 
-
=> refactor: 소셜 연동 중복 가입 못하게 리팩토링

src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java, src/main/java/com/ureca/snac/trade/repository/TradeRepository.java, src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java, src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java, src/main/java/com/ureca/snac/trade/service/TradeFacade.java, src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java, src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java, src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java, src/main/java/com/ureca/snac/trade/service/interfaces/TradeProgressService.java, src/main/java/com/ureca/snac/trade/service/interfaces/TradeQueryService.java, src/main/java/com/ureca/snac/trade/service/response/TradeIdResponse.java, src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
1. 거래 시작 시 tradeId를 반환
2. 거래 조회를 위한 api 추가
3. 거래 수락 전 카드가 삭제되는 문제 수정
4. 실시간 매칭 거래 구매 확정 시 카드가 삭제되도록 처리
5. 판매자 강제종료 후 거래 정리 로직이 동작하지 않는 문제 해결
- 거래 수락 전 카드가 삭제되는 문제 수정
- 판매자의 글이 삭제되면 판매자가 글을 다시 작성해야 하므로 ux 적으로 문제가 있다고 판단하여 수정 함
- 실시간 매칭 거래 구매 확정 시 카드가 삭제되도록 처리
- 실시간 매칭이 종료되면 해당 카드는 사용하지 않는 데이터이므로 제거  
- 판매자 강제종료 후 거래 정리 로직이 동작하지 않는 문제는 제거 플로우가 카드를 제거 후 거래를 제거하여 문제가 발생
- 
-
=> [feat] 실시간 거래 매칭 예외 케이스 수정

src/main/java/com/ureca/snac/asset/entity/TransactionCategory.java, src/main/java/com/ureca/snac/board/controller/ArticleController.java, src/main/java/com/ureca/snac/board/controller/ArticleControllerSwagger.java, src/main/java/com/ureca/snac/board/controller/request/CreateArticleRequest.java, src/main/java/com/ureca/snac/board/controller/request/UpdateArticleRequest.java, src/main/java/com/ureca/snac/board/entity/Article.java, src/main/java/com/ureca/snac/board/exception/ArticleNotFoundException.java, src/main/java/com/ureca/snac/board/repository/ArticleRepository.java, src/main/java/com/ureca/snac/board/repository/ArticleRepositoryCustom.java, src/main/java/com/ureca/snac/board/repository/ArticleRepositoryImpl.java, src/main/java/com/ureca/snac/board/service/ArticleService.java, src/main/java/com/ureca/snac/board/service/ArticleServiceImpl.java, src/main/java/com/ureca/snac/board/service/response/ArticleResponse.java, src/main/java/com/ureca/snac/board/service/response/CreateArticleResponse.java, src/main/java/com/ureca/snac/board/service/response/ListArticleResponse.java, src/main/java/com/ureca/snac/board/service/response/UpdateArticleResponse.java, src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/common/s3/S3Path.java, src/main/java/com/ureca/snac/common/s3/S3Uploader.java, src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java, src/main/resources/application.yml
1. 파일업로드 크기 변경
2. 게시글 업로드, 수정, 삭제, 조회 기능 구현
3. 실시간 거래 기록 추가 및 거래 취소 시 거래 내역이 반영되지 않는 문제 해결
- 파일 업로드 크기를 기존 디폴트 1MB에서 10MB, 30MB로 변경했습니다.
- 게시글 : 대표 이미지 파일, 내용, 제목을 업로드, 수정이 가능합니다.
- 게시글 : 게시글 삭제시 기존 업로드한 파일 또한 삭제됩니다.
- 거래 기록 : 누락한 거래 기록 부분을 추가했습니다. 또한 취소시 거래 내역에 반영되지 않는 문제를 해결 했습니다.
- 
-
=> Qi1 117 게시글 생성 조회 수정 삭제 api 개발

src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/favorite/controller/FavoriteController.java, src/main/java/com/ureca/snac/favorite/controller/FavoriteSwagger.java, src/main/java/com/ureca/snac/favorite/dto/FavoriteCheckResponse.java, src/main/java/com/ureca/snac/favorite/service/FavoriteService.java, src/main/java/com/ureca/snac/favorite/service/FavoriteServiceImpl.java, src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java, src/main/java/com/ureca/snac/trade/controller/BasicTradeControllerSwagger.java, src/main/java/com/ureca/snac/trade/dto/TradeConfirmResponse.java, src/main/java/com/ureca/snac/trade/dto/TradeDto.java, src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java, src/main/java/com/ureca/snac/trade/service/TradeFacade.java, src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java, src/main/java/com/ureca/snac/trade/service/interfaces/TradeProgressService.java
1. 거래확정 API 기능 확장 (일반 거래와 실시간 둘다 적용)
2. 단골 여부 확인 API 추가
- 거래 확정 API 개선은 void 에서 가져오는 응답 객체가 없었는데 단골을 등록하기 위한
현재 단골 등록여부를 내려주는 응답 DTO 생성
- 불필요한 DB 재조회를 제거했음
- 단골 여부 확인 API를 통해 여부를 확인해서 
- /api/favorites/check API에 응답 DTO 결과를 보내서 단골등록 여부를 따질 수 있다.
- 이미 단골이다 라고 뜨거나 단골로 등록하겠냐는 팝업 정도 고려해보면 될듯
=> [feat] 단골 여부 api

src/main/java/com/ureca/snac/favorite/controller/FavoriteController.java, src/main/java/com/ureca/snac/favorite/controller/FavoriteSwagger.java, src/main/java/com/ureca/snac/favorite/dto/FavoriteListRequest.java, src/main/java/com/ureca/snac/favorite/repository/FavoriteRepository.java, src/main/java/com/ureca/snac/favorite/repository/FavoriteRepositoryCustom.java, src/main/java/com/ureca/snac/favorite/repository/FavoriteRepositoryCustomImpl.java, src/main/java/com/ureca/snac/favorite/service/FavoriteService.java, src/main/java/com/ureca/snac/favorite/service/FavoriteServiceImpl.java
1. 단골 목록 조회 API 리팩토링 
2. 커서 기반 페이지네이션 로직 개선
3. 요청 DTO
- Favorite 도메인의 목록 조회 방식을 Asset 도메인과 통일
- 기존의 복합 파라미터 방식에서, 단일 String을 사용하는 커서(Opaque Cursor) 방식으로 변경
=> [refactor] 단골 api cursor 및 slice 적용

src/main/java/com/ureca/snac/auth/exception/UnsupportedSocialProviderException.java, src/main/java/com/ureca/snac/auth/oauth2/SocialProvider.java, src/main/java/com/ureca/snac/auth/repository/AuthRepository.java, src/main/java/com/ureca/snac/auth/service/CustomOAuth2UserService.java, src/main/java/com/ureca/snac/auth/service/JoinServiceImpl.java, src/main/java/com/ureca/snac/auth/service/SocialLoginServiceImpl.java, src/main/java/com/ureca/snac/auth/service/unlink/GoogleUnlinkServiceImpl.java, src/main/java/com/ureca/snac/auth/service/unlink/KakaoUnlinkServiceImpl.java, src/main/java/com/ureca/snac/auth/service/unlink/NaverUnlinkServiceImpl.java, src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/member/Member.java, src/main/java/com/ureca/snac/mypage/dto/MyPageResponse.java
SocialProvider 통합 및 소셜 로그인/연동 로직 리팩토링
Member 엔티티에 updateSocialId 및 isConnected 메서드 추가
AuthRepository에 findBySocialProviderId 메서드 도입 및 중복 메서드 제거
CustomOAuth2UserService, SocialLoginServiceImpl, UnlinkServiceImpl 등에서 SocialProvider enum 사용으로 분기 로직 개선
UnsupportedSocialProviderException 및 BaseCode 리팩토링
MyPageResponse DTO에서 소셜 연결 상태 판별 로직을 엔티티 메서드 호출로 변경
com.ureca.snac.auth.oauth2.SocialProvider 에서 fromValue 메서드 도입, 지원하지 않는 값에 UnsupportedSocialProviderException 발생
기존 문자열 비교 대신 enum 기반 분기 처리로 안정성 향상
updateSocialId(SocialProvider, String) 메서드로 provider별 ID 업데이트 로직 통합
isConnected(SocialProvider) 메서드 추가하여 소셜 연결 여부 확인 책임을 엔티티로 이전
findBySocialProviderId(SocialProvider, String) 메서드로 한 번에 조회하도록 변경
기존 findByNaverId·findByGoogleId·findByKakaoId 중복 정의 제거
CustomOAuth2UserService에서 registrationId → …
=> refactor: SocialProvider 통합 및 소셜 로그인/연동 로직 리팩토링

src/main/java/com/ureca/snac/board/service/response/ArticleResponse.java
1. 게시글 제목이 누락되는 문제를 수정했습니다.
- 
- 
-
=> fix: 게시글 제목이 누락되는 문제 해결

src/main/java/com/ureca/snac/board/controller/ArticleController.java, src/main/java/com/ureca/snac/board/controller/ArticleControllerSwagger.java, src/main/java/com/ureca/snac/board/repository/ArticleRepository.java, src/main/java/com/ureca/snac/board/service/ArticleService.java, src/main/java/com/ureca/snac/board/service/ArticleServiceImpl.java, src/main/java/com/ureca/snac/board/service/response/CountArticleResponse.java, src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/member/controller/MemberController.java, src/main/java/com/ureca/snac/member/controller/MemberControllerSwagger.java, src/main/java/com/ureca/snac/member/dto/response/CountMemberResponse.java, src/main/java/com/ureca/snac/member/repository/MemberRepository.java, src/main/java/com/ureca/snac/member/service/MemberService.java, src/main/java/com/ureca/snac/member/service/MemberServiceImpl.java
1. 전체 게시글 수 조회를 위한 API를 추가했습니다.
2. 전체 회원 수 조회를 위한 API를 추가했습니다.
- 
- 
-
=> [feat] retrieve members and posts count

src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/trade/controller/TradeDurationStatisticController.java, src/main/java/com/ureca/snac/trade/controller/TradeDurationStatisticControllerSwagger.java, src/main/java/com/ureca/snac/trade/entity/TradeDurationStatistic.java, src/main/java/com/ureca/snac/trade/exception/TradeDurationStatisticNotFoundException.java, src/main/java/com/ureca/snac/trade/repository/TradeDurationStatisticRepository.java, src/main/java/com/ureca/snac/trade/repository/TradeRepository.java, src/main/java/com/ureca/snac/trade/scheduler/TradeDurationScheduler.java, src/main/java/com/ureca/snac/trade/service/TradeDurationStatisticServiceImpl.java, src/main/java/com/ureca/snac/trade/service/interfaces/TradeDurationStatisticService.java, src/main/java/com/ureca/snac/trade/service/response/TradeDurationStatisticResponse.java
1. 실시간 매칭 거래의 소요 시간을 통계로 저장하고, 최신 통계 데이터를 조회할 수 있는 API를 추가했습니다.
- 실시간 매칭 거래 소요 시간이 집계되어 주기적으로 통계 테이블에 저장됩니다.
- 가장 최근의 거래 소요 시간 통계 데이터를 조회하는 GET API(/api/trade-duration-statistics)를 구현했습니다.
- 
-
=> [feat] 실시간 매칭 거래 소요 시간 통계 기능

src/main/java/com/ureca/snac/common/RedisKeyConstants.java, src/main/java/com/ureca/snac/config/WebConfigRabbitMQ.java, src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
1. 동일 계정으로 여러 번 소켓 연결 시도를 차단하는 로직 추가
- ChannelInterceptor의 preSend에서 Redis를 이용한 중복 연결 체크 구현
- 이미 연결된 계정으로 또 연결을 시도하면 예외 발생 및 STOMP ERROR 프레임 전송
- disconnect 이벤트 발생 시 단일 연결 키 삭제로 정상 연결 재허용
- 멀티 인스턴스(분산) 환경에서도 안전하게 동작하도록 설계
- 
-
=> [feat] 동일 계정의 소켓 다중 연결 방지 로직 추가

src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
1. 기존 구매글에서 결제완료 후 판매자와 거래시작을 안했다면 거래취소 요청시 즉시 거래 취소 되도록 하였습니다.
- 거래 취소 신청 시 즉시 거래 캔슬
- 카드도 캔슬
- 추후 중복코드 개선
- 
-
=> feat: 아직 판매자를 찾지않은 구매글(카드)는 즉시 삭제 가능하도록 변경

src/main/java/com/ureca/snac/trade/repository/TradeCancelRepository.java, src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java, src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java, src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
1. 기존에 거래취소되면 tradeCancel에만 사유가 들어가던걸 trade에도 들어가도록 수정했습니다.
2. 거래 내역 조회 시 취소 요청 상태 확인 할 수 있도록 변경했습니다.
-  단순히 취소 요청 상태를 status로만 처리하기엔 취소요청은 보조 프로세스로 보는게 맞다고 판단했습니다.
- 이미 존재하는 tradeCancel 과의 정합성 문제도 있을거 같아서
- scrollTrades 시 취소요청된 거래를 불린으로 표시하고 취소사유도 함께 나타나도록 했습니다. 
- 
-
=> [feat] 취소 사유기능 수정, 거래 내역 조회 시 취소 요청 상태 조회 추가

src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/trade/controller/AttachmentController.java, src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java, src/main/java/com/ureca/snac/trade/controller/DisputeController.java, src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java
- 이미지 첨부 api 앤드포인트 개선
- 업로드 용 url api 에서 리턴값에 s3key 포함하도록 수정
- 문의 조회 시 거래아이디가 없으므로 null 로 들어가도록 처리
- 기타 사소한 수정
반환값 명시
basecode 명시
- 
- 
-
=> [feat] 이미지 업로드 및 조회 관련 수정

src/main/java/com/ureca/snac/trade/controller/DisputeController.java, src/main/java/com/ureca/snac/trade/controller/DisputeControllerSwagger.java, src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
1. 사용자의 신고(문의) api 에 대한 스웨거 작성했습니다.
2. 기존에 본인 카드를 본인이 취소하면 카드를 캔슬 처리했는데 삭제되도록 변경했습니다.
- 
- 
-
=> [feat] 신고(문의) 사용자 api 스웨거 작성,  카드캔슬처리 대신 카드삭제 처리

src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java, src/main/java/com/ureca/snac/trade/controller/DisputeAdminControllerSwagger.java, src/main/java/com/ureca/snac/trade/dto/DisputeSearchCond.java, src/main/java/com/ureca/snac/trade/dto/dispute/DisputeDetailResponse.java, src/main/java/com/ureca/snac/trade/dto/dispute/MyDisputeListItemDto.java, src/main/java/com/ureca/snac/trade/entity/Dispute.java, src/main/java/com/ureca/snac/trade/entity/DisputeAttachment.java, src/main/java/com/ureca/snac/trade/entity/DisputeCategory.java, src/main/java/com/ureca/snac/trade/entity/DisputeStatus.java, src/main/java/com/ureca/snac/trade/entity/DisputeType.java, src/main/java/com/ureca/snac/trade/repository/DisputeRepositoryImpl.java, src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java, src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java, src/main/java/com/ureca/snac/trade/service/interfaces/DisputeAdminService.java
1. 신고(문의) 관리자 기능 스웨거 작성했습니다.
2. 관리자 신고(문의) 처리 중 기각이 불필요 할 것 같아 제외했습니다.
3. dispute에 카테고리 필드를 추가했습니다.
4. 신고(문의) 검색 기능 추가
- 기각을 처리한 이유는 상태처리에서는 단순히 답변만 하며 이는 후처리를 하든 기각을 하든 동일합니다.
- 떄문에 기각을 제거하고 답변을 했다면 이후 패널티, 환불, 취소, 원상복구 등 관리자가 후처리기능을 통해 처리합니다.
- 신고만 고려하고 만들었던 엔티티이기 때문에 추가적으로 문의가 들어오며 구별하는데 불편함이 있었는데 카테고리 필드를 추가하여 구분할 수 있도록 했습니다.
- 
-
=> [feat] 신고(문의) 관리 기능 스웨거 작성, 관리자 기능 수정 및 dispute 카테고리 필드추가

src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java, src/main/java/com/ureca/snac/trade/controller/DisputeAdminControllerSwagger.java, src/main/java/com/ureca/snac/trade/dto/dispute/DisputeStatisticsResponse.java, src/main/java/com/ureca/snac/trade/repository/DisputeRepository.java, src/main/java/com/ureca/snac/trade/repository/TradeCancelRepository.java, src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java, src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java, src/main/java/com/ureca/snac/trade/service/interfaces/DisputeAdminService.java
1. 신고(문의)의 카테고리별 타입별 count를 볼 수 있도록 기능 추가했습니다.
2. 기존 거래 단건 조회 시 신고정보가 안나오던 문제가 있어 수정했습니다.
- 
- 
-
=> [feat] dispute 카테고리 별 타입 별 통계 기능 추가, 거래 조회 시 신고정보 불러오기

src/main/java/com/ureca/snac/auth/oauth2/CustomOAuth2FailHandler.java, src/main/java/com/ureca/snac/auth/service/CustomOAuth2UserService.java, src/main/java/com/ureca/snac/common/BaseCode.java
소셜 로그인 예외 처리 개선 및 에러 코드 추가
- 새로운 에러 코드 추가 (`OAUTH_DB_ALREADY_LINKED`, `OAUTH_DB_ACCOUNT_NOT_FOUND`)
- 소셜 로그인 시 이미 연동된 계정, 미연동 계정 예외에 대해 명확한 에러 메시지 처리
- `CustomOAuth2FailHandler`에서 실패 시 에러 코드 파라미터를 포함하여 리디렉션 처리 추가
- 로그 메시지 및 예외 처리 로직 개선으로 디버깅 효율성 향상
- 
-
=> feat: 소셜 로그인 예외 처리 개선 및 에러 코드 추가

src/main/java/com/ureca/snac/trade/entity/TradeCancel.java, src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java, src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
- 기존에 판매자가 구매자의 취소요청을 기각하면 판매자가 다시 취소요청이 불가했던 문제를 수정했습니다
- 
- 
-
=> [feat] 판매자가 구매자 취소요청 기각 후 판매자 취소요청 가능하게 수정
