.github/workflows/deploy.yml, src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/common/CommonController.java, src/main/resources/application.yml
1. GithubActions, S3, ECR, CodeDeploy를 이용한 CI / CD 배포 파이프라인을 구축했습니다.
2. Health Check API 추가했습니다.
- 
- 
-
=>  [chore] CI/CD 초기 세팅

build.gradle, settings.gradle
1.   health check 도입 
-  spring acutator dependencies
- 
-
=> [feat] add Actuator for health check

.gitignore, src/main/java/com/ureca/snac/member/MemberRepository.java
1.  관련 기능 개발을 위한 MemberRepository 인터페이스를 추가했습니다.
2.  gitignore에 env 추가
- 인터페이스 추가
- 
-
=> [feat] create MemberRepository

src/main/java/com/ureca/snac/common/ApiResponse.java, src/main/java/com/ureca/snac/common/BaseCode.java, src/main/java/com/ureca/snac/common/advice/GlobalAdvice.java, src/main/java/com/ureca/snac/common/advice/ValidationErrorResponse.java, src/main/java/com/ureca/snac/common/advice/ValidationErrorResponseWrapper.java, src/main/java/com/ureca/snac/finance/service/BankService.java
1. Validation 예외 처리 로직 구현
- @Validated 기반 유효성 검사 로직을 Bank API에 적용
- MethodArgumentNotValidException을 처리하여 필드 오류와 글로벌 오류를 구분해 ValidationErrorResponseWrapper로 응답
- 
-
=> [feat] 은행 유효성 검증 처리 및 에러 응답 구조 개선

src/main/java/com/ureca/snac/auth/dto/CustomUserDetails.java, src/main/java/com/ureca/snac/auth/service/JoinServiceImpl.java, src/main/java/com/ureca/snac/auth/service/ReissueServiceImpl.java, src/main/java/com/ureca/snac/money/controller/MoneyRechargeController.java, src/main/java/com/ureca/snac/money/controller/MoneyRechargeSwagger.java
1. CustomUserDetails 
- conflict dto 필드
=> [fix] conflict sol

src/main/java/com/ureca/snac/money/controller/MoneyRechargeController.java, src/main/java/com/ureca/snac/money/service/MoneyService.java, src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java
1. 에러 발생~ 유령객체 가져오는 임시코드 해결
- TransientPropertyValueException 해결을 위해서 getMember인 유령 객체를 가져오지말고
고유키 값인 email을 가져와서 Member 식별한다.
- 
-
=> fix: solve TransientPropertyValueException

src/main/resources/application.yml
=> [fix] RabbitMQ 설정 오류 수정

src/main/resources/application.yml
=> [hotfix] RabbitMQ 접속 설정 수정

src/main/java/com/ureca/snac/trade/entity/Trade.java
=> [hotfix] payment_type 컬럼 제거

src/main/java/com/ureca/snac/auth/config/SecurityConfig.java
=> [chore] 테스트 서버 CORS 문제 해결

src/main/java/com/ureca/snac/auth/dto/response/NaverResponse.java, src/main/resources/application.yml
1. OAuth 리디렉션 URI를 환경 변수로 변경
2. NaverResponse 생성자에서 unchecked 캐스트 경고 억제
- 
- 
-
=> hotfix: OAuth 리디렉션 URI를 환경 변수로 변경

build.gradle, src/main/java/com/ureca/snac/board/controller/CardControllerSwagger.java, src/main/java/com/ureca/snac/board/repository/CardRepositoryImpl.java, src/main/java/com/ureca/snac/common/RedisKeyConstants.java, src/main/java/com/ureca/snac/config/RedissonConfig.java, src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
1. 소켓 연결 종료 시 동시성 문제를 방지하기 위해 분산 락을 적용하였습니다.
2. 실시간 판매 카테고리 카드는 일반 카드 조회에서 제외되도록 수정하였습니다.
- 
- 
-
=> [feat] 분산락 적용 및 카드 조회 조건 수정

src/main/java/com/ureca/snac/auth/config/SecurityConfig.java
hotfix: "https://www.snac-app.com" CORS 허용
- 
- 
-
=> hotfix: "https://www.snac-app.com" CORS 허용

src/main/java/com/ureca/snac/board/dto/CardDto.java, src/main/java/com/ureca/snac/notification/listener/NotificationListener.java, src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java, src/main/java/com/ureca/snac/trade/dto/TradeDto.java, src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java, src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java, src/main/java/com/ureca/snac/trade/service/interfaces/TradeCancelService.java
=> [refactor] 모호한 dto id 수정

src/main/java/com/ureca/snac/trade/controller/MatchingController.java, src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java, src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
1. 실시간 거래시 파라미터를 잘못된 값을 전달하여 카드가 삭제되지 않는 문제를 해결
2. 거래 신청 보내기전 구매자가 스스로 자기 필터를 지울 수 있는 api 추가
- 
- 
-
=> [fix, feat] 실시간 거래시 카드가 삭제되지 않는 문제 및 구매자 필터 삭제 기능 구현

src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
1. 카드 생성 시 알림 기능 추가
- 기존 실시간 매칭 시 카드 생성 후 카드 정보가 내려오지 않아 취소가 불가능했던 문제를 해결했습니다.
- 
-
=> [feat] 카드 생성 시 알림 기능 추가

src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
=> [fix] 카드 생성 후 본인 알림 누락 문제 해결

src/main/java/com/ureca/snac/board/controller/CardController.java, src/main/java/com/ureca/snac/board/controller/CardControllerSwagger.java, src/main/java/com/ureca/snac/board/repository/CardRepositoryCustom.java, src/main/java/com/ureca/snac/board/repository/CardRepositoryImpl.java, src/main/java/com/ureca/snac/board/service/CardService.java, src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
1. 본인이 작성한 구매글 및 판매글 조회 API 추가
- 
- 
-
=> [feat] 본인이 작성한 구매글 및 판매글 조회 API 추가

src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java, src/main/java/com/ureca/snac/trade/controller/DisputeController.java, src/main/java/com/ureca/snac/trade/dto/DisputeSearchCond.java, src/main/java/com/ureca/snac/trade/repository/DisputeRepository.java, src/main/java/com/ureca/snac/trade/repository/DisputeRepositoryCustom.java, src/main/java/com/ureca/snac/trade/repository/DisputeRepositoryImpl.java, src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java, src/main/java/com/ureca/snac/trade/service/interfaces/DisputeAdminService.java
1. 조건별 검색 기능
2. 처리 대기중인 신고 조회
3. 상세 조회
-1. 쿼리dsl 을 이용하여 신고 상태, 신고 타입, 신고자 필터링 조회기능을 추가했습니다.
-2. 관리자 작업을 위해 현재 처리 대기중인 신고 조회  기능을 추가했습니다.
- 3. admin 컨트롤러에 상세조회 앤드포인트 추가했습니다
- 
-
=> [feat] 어드민 신고 관련 api 추가 구성

src/main/java/com/ureca/snac/board/entity/Card.java, src/main/java/com/ureca/snac/trade/entity/Trade.java, src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
1. TradeInitiationServiceImpI 서비스 계층에 있는 검증 및 변환 로직을 도메인으로 위임하여 서비스단 코드를 리팩토링 했습니다.
- 
- 
-
=> [refactor] trade initiation service

src/main/java/com/ureca/snac/board/entity/Card.java, src/main/java/com/ureca/snac/board/service/CardServiceImpl.java, src/main/java/com/ureca/snac/trade/entity/Trade.java, src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java, src/main/java/com/ureca/snac/trade/service/interfaces/TradeProgressService.java
1. TradeProgressServiceImpI 서비스 계층에 있는 검증 및 변환 로직을 도메인으로 위임하여 서비스단 코드를 리팩토링 했습니다.
- 
- 
-
=> [refactor] trade progress service

build.gradle, src/main/java/com/ureca/snac/config/ShedLockConfig.java, src/main/java/com/ureca/snac/trade/scheduler/TradeStatisticsScheduler.java, src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java, src/main/resources/application.yml
1. 다중 인스턴스 환경에서 스케줄러가 중복 실행되는 문제를 분산 락(ShedLock) 적용으로 해결했습니다.
2. 구매글 등록 시 seller가 없는 경우 조회 시 발생하는 NPE 문제를 방어 로직 추가로 해결했습니다.
- 
- 
-
=> [feat, fix] scheduling lock

src/main/java/com/ureca/snac/auth/service/SocialLoginServiceImpl.java, src/main/java/com/ureca/snac/auth/service/unlink/GoogleUnlinkServiceImpl.java
=> fix : Add transactional annotation to social login service

src/main/java/com/ureca/snac/config/RabbitMQConfig.java, src/main/java/com/ureca/snac/config/WebConfigRabbitMQ.java, src/main/java/com/ureca/snac/notification/listener/NotificationListener.java, src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java, src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
1. 스케줄러 서버를 프로파일을 이용하여 분리했습니다.
- 
- 
-
=> [feat] 스케줄러 서버 프로파일 분리

src/main/java/com/ureca/snac/member/entity/Member.java, src/main/resources/application.yml
hotfix: 개발을 위해 jwt 토큰 시간 임시로 대폭 늘리고, 닉네임 변경 가능 시간도 마찬가지로 대폭 줄임 
- 
- 
-
=> hotfix: 개발을 위해 jwt 토큰 시간 임시로 대폭 늘리고, 닉네임 변경 가능 시간도 마찬가지로 대폭 줄임

src/main/java/com/ureca/snac/notification/listener/NotificationListener.java, src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
1. 신고 알림 WebSocket 리스너 추가했습니다.
2. 신고자 및 피신고자 모두에게 신고 알림 전송 기능 추가했습니다.
- 
- 
-
=> [feat] 신고 알림 WebSocket 리스너 추가

src/main/java/com/ureca/snac/board/repository/CardRepository.java, src/main/java/com/ureca/snac/board/service/CardServiceImpl.java, src/main/java/com/ureca/snac/trade/repository/TradeRepository.java, src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java, src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java, src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
1. 실시간 거래 자동 정리 로직에서 불필요한 락을 제거했습니다.
2. 거래 로직에서 불필요한 락을 제거했습니다.
- 멘토링 답변 결과 락이 많다는 의견이 많아 비지니스 로직을 분석 후 불필요한 락을 제거했습니다. 
- 
-
=> [refactor] 거래 로직에서 불필요한 락 제거

src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java
1. 구매자 일 경우 판매자에 대한 ID NPE 발생
- 삼항 조건문 대신 조건 분기 추가해서 해결
=> [hotfix] 구매자 일 경우 판매자에 대한 ID NPE

src/main/java/com/ureca/snac/trade/support/TradeMessageBuilder.java
=> [fix] 불필요한 카드 조회 제거

src/main/java/com/ureca/snac/dev/controller/DevToolController.java, src/main/java/com/ureca/snac/dev/infra/FakePaymentGatewayAdapter.java, src/main/java/com/ureca/snac/dev/service/DevToolServiceImpl.java, src/main/java/com/ureca/snac/infra/TossPaymentsAdapter.java
1. 어댑터 매핑 오류 해결
-  Profile설정으로 prod 환경과 dev 환경 분리 였던 결과를 Primary 랑 Qualifier 로 해결
-  스프링 시큐리티에서 관리자로 해서 DEV 접근
-
=> [hotfix] Profile -> Primary 및 Qualifier 사용으로 해결

src/main/java/com/ureca/snac/auth/listener/EmailListenerServiceImpl.java, src/main/java/com/ureca/snac/auth/listener/SmsListenerServiceImpl.java
=> [chore] SMS 거래 리스너 제거

src/main/java/com/ureca/snac/trade/dto/TradeDto.java, src/main/java/com/ureca/snac/trade/dto/dispute/DisputeDetailResponse.java, src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java, src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java
1.  신고(문의) 시 닉네임 조회 되도록 했습니다.
2. 어드민일경우 상대방도 뜨고
3. 어드민아니면 상대방은 안뜨고
- 
- 
-
=> [feat] 어드민 신고 조회 시 닉네임 함께 내려주기

src/main/java/com/ureca/snac/trade/support/TradeMessageBuilder.java
=> [fix] 취소시 문자가 안오는 문제 해결

src/main/java/com/ureca/snac/asset/service/AssetHistoryEventListener.java, src/main/java/com/ureca/snac/member/service/MemberJoinEventListener.java
1. @Profile("!scheduler") 누락 해결
=> [hotfix] @Profile

src/main/java/com/ureca/snac/auth/filter/JWTFilter.java
1. chore: JWTFilter 로그 제거.
- 
- 
-
=> chore: JWTFilter 로그 제거.

src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java, src/main/java/com/ureca/snac/trade/dto/dispute/DisputeDetailResponse.java, src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java, src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java, src/main/java/com/ureca/snac/trade/service/interfaces/DisputeAdminService.java
신고조회 시 거래 정보가 내려오지 않던 오류 수정 했습니다
- 
- 
-
=> [feat] 신고조회 시 거래 정보가 내려오지 않던 오류 수정
